# Generated by Django 5.1.4 on 2025-01-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='company',
        ),
    ]
