# Generated by Django 5.1.4 on 2025-01-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nationalities_patient_nationality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='nationality',
            new_name='nationalities',
        ),
    ]
