# Generated by Django 5.1.4 on 2025-01-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nationality_patient_nationalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Single', 'Célibataire'), ('Married', 'Marié(e)'), ('Widowed', 'Veuf(vue)'), ('Divorced', 'Divorcé(e)')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('relative_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('relative_same_address', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.patients'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='core.patients', verbose_name='Patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
