# Generated by Django 5.1.4 on 2025-01-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patients_alter_consultation_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='nationality',
        ),
    ]
