# Generated by Django 5.1.4 on 2025-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_patients_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='convention_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='has_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='is_conventioned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
