# Generated by Django 5.1.4 on 2025-01-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patients_convention_provider_patients_has_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultations', models.ManyToManyField(blank=True, to='core.consultation')),
                ('examinations', models.ManyToManyField(blank=True, to='core.examen')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.patients')),
                ('prescriptions', models.ManyToManyField(blank=True, to='core.prescription')),
                ('sign_vitals', models.ManyToManyField(blank=True, to='core.vitalsigns')),
            ],
        ),
    ]
