# Generated by Django 5.1.4 on 2025-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/medical_records/'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
