# Generated by Django 5.1.4 on 2025-01-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medicalrecord_file_medicalrecord_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='note',
            new_name='notes',
        ),
    ]
