# Generated by Django 5.1.4 on 2025-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_note_medicalrecord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
