# Generated by Django 5.1.4 on 2025-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_medicalrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('En attente', 'Pending'), ('terminé', 'Completed'), ('Annulé', 'Cancelled'), ('En consultation', 'In consultation'), ('Terminé', 'Done')], default='pending', max_length=20, null=True),
        ),
    ]
