# Generated by Django 5.1.4 on 2025-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_consultation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('En attente de consultation', 'En attente de consultation'), ('En cours de consultation', 'En cours de consultation'), ('Consultation terminée', 'Consultation terminée'), ('Consultation annulée', 'Consultation annulée')], default='En attente de consultation', max_length=50),
        ),
    ]
