# Generated by Django 5.1.4 on 2025-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='consultation_status',
            field=models.CharField(choices=[('En attente de consultation', 'En attente de consultation'), ('Consultation effectuée', 'Consultation effectuée'), ('Consultation annulée', 'Consultation annulée'), ('Consultation terminée', 'Consultation terminée')], default='En attente de consultation', max_length=255),
        ),
    ]
