# Generated by Django 5.1.4 on 2025-01-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_patients_consultation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='gender',
        ),
    ]
