# Generated by Django 5.1.4 on 2025-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appoitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoitement',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoitement',
            name='date_rdv',
            field=models.DateField(),
        ),
    ]
