# Generated by Django 5.1.4 on 2025-02-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appoitement_time_alter_appoitement_date_rdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoitement',
            old_name='date_rdv',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appoitement',
            old_name='medecin',
            new_name='doctor',
        ),
    ]
