# Generated by Django 5.1.4 on 2025-03-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_appoitement_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='care_type',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
