# Generated by Django 5.1.4 on 2025-03-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_department_care_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='convention_provider',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='has_insurance',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_conventioned',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='json_data',
        ),
    ]
