# Generated by Django 5.1.4 on 2025-03-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_patients_convention_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='relative_same_address',
            new_name='relative_address',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='relative_mobile',
        ),
    ]
