# Generated by Django 5.1.4 on 2025-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_relative_same_address_patients_relative_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='relative_address',
            field=models.TextField(default=False),
        ),
    ]
