# Generated by Django 5.1.4 on 2025-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_patients_relative_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, null=True),
        ),
    ]
