# Generated by Django 5.1.4 on 2025-09-04 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_consultation_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('cancelled_by_patient', 'Annulé par le patient'), ('cancelled_by_doctor', 'Annulé par le médecin'), ('completed', 'Terminé'), ('missed', 'Patient non présent')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('patient_notes', models.TextField(blank=True, help_text='Notes ou symptômes décrits par le patient', null=True)),
                ('is_first_visit', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('video_consultation_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time_slot__date', '-time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Durée en minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_teleconsultation', models.BooleanField(default=False)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_appointments', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Durée en minutes')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='appoitement',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appoitement',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='consultations',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.consultation'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='examinations',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.examen'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.prescription'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='sign_vitals',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.vitalsigns'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('En attente', 'Pending'), ('terminé', 'Completed'), ('Annulé', 'Cancelled'), ('En consultation', 'In consultation'), ('Terminé', 'Done')], default='En attente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['number'], name='core_medica_number_2d34dd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['status'], name='core_medica_status_1c8e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='core_medica_created_def948_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patients'),
        ),
        migrations.AddField(
            model_name='consultationreason',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_reasons', to='core.specialty'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultationreason'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultationreason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.timeslot'),
        ),
        migrations.DeleteModel(
            name='Appoitement',
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'date', 'is_available'], name='core_timesl_doctor__d3be98_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'is_available'], name='core_timesl_date_67bb19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
