# Generated by Django 5.1.4 on 2025-09-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appointment_consultationreason_doctorschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'permissions': [('archive_medical_record', 'Peut archiver un dossier médical'), ('reactivate_medical_record', 'Peut réactiver un dossier médical'), ('view_archived_records', 'Peut voir les dossiers archivés')], 'verbose_name': 'Dossier médical', 'verbose_name_plural': 'Dossiers médicaux'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='file',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priorité du dossier (0 = normale)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('in_consultation', 'En consultation'), ('completed', 'Terminé'), ('archived', 'Archivé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_records/%Y/%m/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_result', 'Résultat de laboratoire'), ('xray', 'Radiographie'), ('scan', 'Scanner'), ('mri', 'IRM'), ('ultrasound', 'Échographie'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de fichier')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier médical',
                'verbose_name_plural': 'Fichiers médicaux',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='core.medicalfile'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'status'], name='core_medica_patient_f5d069_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['archived_at'], name='core_medica_archive_cff348_idx'),
        ),
    ]
