# Generated by Django 5.1.4 on 2025-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_patient_alter_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='relative_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='relative_phone',
            new_name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='relative_address',
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
