# Generated by Django 5.1.4 on 2025-09-07 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_relative_name_patients_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Message de la notification')),
                ('notification_type', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('warning', 'Avertissement'), ('info', 'Information')], default='info', help_text='Type de notification (success, error, warning, info)', max_length=20)),
                ('category', models.CharField(choices=[('appointment', 'Rendez-vous'), ('prescription', 'Prescription'), ('billing', 'Facturation'), ('medical_record', 'Dossier médical'), ('system', 'Système'), ('reminder', 'Rappel'), ('emergency', 'Urgence')], default='system', help_text='Catégorie de la notification', max_length=30)),
                ('is_read', models.BooleanField(default=False, help_text='Indique si la notification a été lue')),
                ('is_important', models.BooleanField(default=False, help_text='Indique si la notification est importante')),
                ('is_system_generated', models.BooleanField(default=True, help_text='Indique si la notification est générée automatiquement par le système')),
                ('action_url', models.URLField(blank=True, help_text='URL vers laquelle rediriger lors du clic sur la notification', null=True)),
                ('action_text', models.CharField(blank=True, help_text="Texte du bouton d'action", max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date de lecture de la notification', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la notification", null=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Médecin concerné par la notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.doctor')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient destinataire de la notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.patients')),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur destinataire de la notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['patient', 'is_read'], name='core_notifi_patient_f68e6e_idx'), models.Index(fields=['notification_type', 'category'], name='core_notifi_notific_17e2e0_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx')],
            },
        ),
    ]
