# Generated by Django 5.1.4 on 2025-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Designates whether this user must change their password at next login.', verbose_name='must change password'),
        ),
    ]
