# Generated by Django 5.1.4 on 2025-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Designates the gender of the user.', max_length=10, verbose_name='gender'),
        ),
    ]
