# Generated by Django 5.1.4 on 2025-09-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_relative_name_patients_emergency_contact_name_and_more'),
        ('doctors', '0002_alter_consultation_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to='core.patients'),
        ),
    ]
